[package]
name = "auth"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
axum = "0.7.5"
clap = "4"
config = "0.14.0"
dotenv = "0.15"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
tokio = { version = "1.38.0", features = ["full"] }
